name: Reusable workflow deployment

on: 
  workflow_call:
    inputs:
      mongodb_uri:
        required: true
        type: string
      kubectl-version:
          description: provide the required kubectl version
          default: v1.26.0
          required: false
          type: string
      k8s-manifet-dir:
          description: directory containing manifest files
          default: Kubernetes/
          required: false
          type: string
      environment:
          description: provide the deployment environment
          default: dev
          required: false
          type: string
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    environment:
      name: ${{inputs.environment}}
      url: https://${{ steps.set-ingress-host-address.outputs.PP_INGRESS_HOST}}
    outputs:
      APP_INGRESS_URI: ${{ steps.set-ingress-host-address.outputs.PP_INGRESS_HOST}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl cli
        uses: azure/setup-kubectl@v3
        with:
          version: '${{inputs.kubectl-version}}'

      - name: set kubeconfig file
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig}}

      - name: Fetch Kubernetes Cluster details
        run: |
          kubectl version --output=yaml
          echo ----------------------------------------------------
          kubectl get nodes

      - name: Save NGINX Ingress Controller IP as a GITHUB Environment variable.
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace tokens in manifest file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{inputs.k8s-manifet-dir}}/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP}}

      - name: Check files
        run: |
          cat ${{inputs.k8s-manifet-dir}}/*.yaml

      - name: create MongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI=${{ inputs.mongodb_uri}} \
          --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME}} \
          --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password}} \
          --save-config \
          --dry-run=client \
          -o yaml | kubectl apply -f -

      - name: Deploy to DEV environment
        run: |
          kubectl apply -f ${{inputs.k8s-manifet-dir}}

      - name: Set app ingress host URL
        id: set-ingress-host-address
        run: |
          echo "PP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE}} get ingress -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> "$GITHUB_OUTPUT"